### ISSUE TITLE
problems with recipe for horse chopping block

### ISSUE THREAD

**Issue by kotoroshinoto** [ACGaming/HorsePowerTFC#1]
I am using the terrafirmagreg modpack (uses 1.12.2).

from what I've been able to investigate, there is a divide of sorts in the code between the log item and the log block that is placed in world when you right click with it.

It doesn't seem like the automatic log item detection that drives the recipe generation is working correctly.

when I attempt to put the recipe on a crafting table, the server issues an exception: java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.dries007.tfc.objects.items.ItemMisc cannot be cast to net.minecraft.item.ItemBlock

I'm not sure which item is the one actually throwing the error, but if it is the log, I suspect the log item cannot be cast to a block. the TFC code likely handles that automatically behind the scenes without casting (placing the item generates the block which harvesting the block nets the item).

How would this be rectified? Can we use crafttweaker to tell it to use the log block as the texture item while using the log item for the recipe?

Some additional information: looking at the jei entries that were automatically created for the log items, I can pull one out ,but I can't place it in the world without a crash (client side at least), probably related to the same issue of attempting to treat the log item as a block and failing.

I CAN however use the give command as such: /give horsepower:chopper 1 0 {textureBlock: {id:block:tfc:wood/log/oak, Count:1, Damage:0}}, which looks correct and can be placed.

was hoping this would temporarily work around the problem, but something seems to be choking:

https://pastebin.com/HpBr0syB

here is some more of the exception stack trace:

https://pastebin.com/hnx2zGyK

**Comment by kotoroshinoto** [comment]
if I change the zenscript lines to the following:
recipes.removeShaped(<horsepower:chopper>);
recipes.removeShapeless(<horsepower:chopper>);
recipes.addShaped(<horsepower:chopper>.withTag({textureBlock:{id:"block:tfc:wood/log/oak", Count:1, Damage:0}}), [[<minecraft:lead>, <ore:stickWood>, <minecraft:lead>], [<ore:stickWood>, <ore:saw>, <ore:stickWood>], [<ore:stickWood>, <tfc:wood/log/oak>, <ore:stickWood>]]);
mods.jei.JEI.addItem(<horsepower:chopper>.withTag({textureBlock:{id:"block:tfc:wood/log/oak", Count:1, Damage:0}}));

it now shows the recipe in JEI, but the resulting item does not appear in the crafting table output slot.

There is not an error server-side this time, so it isn't invoking the same function that crashed things before. I'm not sure why it doesn't work.

**Comment by ACGaming** [comment]
You're right, there seems to be an issue with the recipe tags. As the codebase is ridiculously complex, I don't know if I can come up with a proper solution soon.

Take a look at this script for a workaround: https://github.com/ACGaming/TerraFirmaCraft-Reditus-2/blob/86c33b915620bff8b4e50f0980ffcb2bb561f024/scripts/horsepower.zs

**Comment by ACGaming** [comment]
Not too sure why there is an explicit casting of the ingredient to a block at this point. Removing that resolves the issue, potential consequences are unknown though.
