### ISSUE TITLE
Crash with grindstone

### ISSUE THREAD

**Issue by Exzept1on** [ACGaming/HorsePowerTFC#2]
It happened on the server. When the player put mica from GTCEu into the grindstone. Which I prescribed a prescription for there. After logging into that chunk, the client and server crashed.

[log.log](https://github.com/ACGaming/HorsePowerTFC/files/7832472/log.log)

**Comment by ACGaming** [comment]
Entity Culling is mentioned in the crash log. Please add `horsepower:grindstone` to `skipHiddenTileEntityRenderingBlacklist` inside Entity Culling's config and see if the issue persists!

**Comment by Exzept1on** [comment]
It looks like it was a error on the GTCEu side and they fixed it. There is no errors anymore. Thanks.

**Comment by ACGaming** [comment]
Alright, thanks for letting me know!
